/* Generated by re2c 1.0.1 on Sun Mar 24 22:19:22 2019 */
#line 1 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.re"
#include <stdio.h>

#include "lexers/lexers.h"
using namespace std;

std::vector<Token> lex_tokens(const char *YYCURSOR)
{
	vector<Token> ans;
	const char *YYMARKER, *o1, *o2;
    const char *start = YYCURSOR;
	const char *yyt1;
	
loop:
    
#line 18 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.cc"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy2;
	case '\t':
	case '\v':
	case ' ':	goto yy6;
	case '\r':	goto yy8;
	case '\'':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = YYCURSOR;
		goto yy9;
	case '(':
		yyt1 = YYCURSOR;
		goto yy12;
	case '*':
	case '+':
	case '-':
	case '/':
	case '^':
		yyt1 = YYCURSOR;
		goto yy14;
	case '.':
		yyt1 = YYCURSOR;
		goto yy16;
	case '0':
		yyt1 = YYCURSOR;
		goto yy18;
	case '<':
	case '=':
	case '>':
		yyt1 = YYCURSOR;
		goto yy19;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'T':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = YYCURSOR;
		goto yy20;
	case 'E':
	case 'e':
		yyt1 = YYCURSOR;
		goto yy23;
	case 'S':
	case 'U':
	case 's':
	case 'u':
		yyt1 = YYCURSOR;
		goto yy24;
	case '\\':
		yyt1 = YYCURSOR;
		goto yy25;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 43 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.re"
	{ return ans; }
#line 130 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.cc"
yy4:
	++YYCURSOR;
yy5:
#line 38 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.re"
	{ 
            Token token(Token_type::INVALID, 0, 0);
            ans.push_back(token); 
            return ans; 
        }
#line 140 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.cc"
yy6:
	++YYCURSOR;
#line 67 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.re"
	{goto loop;}
#line 145 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.cc"
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy2;
	default:	goto yy5;
	}
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
yy10:
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy9;
	case '.':	goto yy16;
	case 'E':
	case 'e':	goto yy26;
	case 'S':
	case 'U':
	case 's':
	case 'u':	goto yy28;
	default:	goto yy11;
	}
yy11:
	o1 = yyt1;
	o2 = YYCURSOR;
#line 52 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.re"
	{ 
            Token token(Token_type::NUMBER_LITERAL, (size_t)(o1 - start), (size_t)(o2 - start));
            ans.push_back(token); 
            goto loop; 
        }
#line 186 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.cc"
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case ')':	goto yy29;
	default:	goto yy12;
	}
yy14:
	++YYCURSOR;
yy15:
	o1 = yyt1;
	o2 = YYCURSOR;
#line 47 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.re"
	{ 
            Token token(Token_type::BI_OPERATOR, (size_t)(o1 - start), (size_t)(o2 - start));
            ans.push_back(token); 
            goto loop; 
        }
#line 204 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.cc"
yy16:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy16;
	case 'E':
	case 'e':	goto yy26;
	default:	goto yy11;
	}
yy18:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'B':
	case 'b':	goto yy31;
	case 'X':
	case 'x':	goto yy32;
	default:	goto yy10;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy14;
	default:	goto yy15;
	}
yy20:
	yych = *++YYCURSOR;
yy21:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy20;
	default:	goto yy22;
	}
yy22:
	o1 = yyt1;
	o2 = YYCURSOR;
#line 62 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.re"
	{ 
            Token token(Token_type::SYMBOL, (size_t)(o1 - start), (size_t)(o2 - start));
            ans.push_back(token); 
            goto loop; 
        }
#line 318 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.cc"
yy23:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\'':	goto yy33;
	case '+':
	case '-':	goto yy35;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy36;
	default:	goto yy21;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy20;
	default:	goto yy11;
	}
yy25:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy38;
	case '\r':	goto yy40;
	default:	goto yy15;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy33;
	case '+':
	case '-':	goto yy35;
	default:	goto yy27;
	}
yy27:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy11;
	case 1: 	goto yy22;
	default:	goto yy15;
	}
yy28:
	++YYCURSOR;
	goto yy11;
yy29:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR;
#line 57 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.re"
	{ 
            Token token(Token_type::LIST_LITERAL, (size_t)(o1 - start), (size_t)(o2 - start));
            ans.push_back(token); 
            goto loop; 
        }
#line 452 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.cc"
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':	goto yy41;
	default:	goto yy27;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy43;
	default:	goto yy27;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy33;
	default:	goto yy11;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy33;
	default:	goto yy27;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':	goto yy33;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy36;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy20;
	default:	goto yy11;
	}
yy38:
	++YYCURSOR;
#line 44 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.re"
	{
            goto loop;
        }
#line 596 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.cc"
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy38;
	default:	goto yy27;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':	goto yy41;
	case 'S':
	case 'U':
	case 's':
	case 'u':	goto yy28;
	default:	goto yy11;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy43;
	case 'S':
	case 'U':
	case 's':
	case 'u':	goto yy28;
	default:	goto yy11;
	}
}
#line 68 "/mnt/c/repos/scalc/build/../lexers/lexer_tokens.re"

}