/* Generated by re2c 1.1.1 on Mon Feb 18 00:42:13 2019 */
#line 1 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
#include <stdio.h>
#include <algorithm>

#include "lexers/lexers.h"
using namespace std;

Number lex_number(const char *YYCURSOR)
{
	vector<Token> ans;
	const char *YYMARKER, *o1, *o2;
    const char *start = YYCURSOR;

	const char *yyt1;
	
loop:
    
#line 20 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = YYCURSOR;
		goto yy6;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 34 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ return Number{}; }
#line 44 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy4:
	++YYCURSOR;
#line 30 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            Number n{};
            return n; 
        }
#line 52 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy6;
	case '.':	goto yy9;
	case 'E':
	case 'e':	goto yy12;
	case 'S':
	case 's':	goto yy14;
	case 'U':
	case 'u':	goto yy15;
	default:	goto yy8;
	}
yy8:
	o1 = yyt1;
	o2 = YYCURSOR;
#line 55 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            auto ans = stoll(s);
            Number n;
            n.set_val_i64(ans);
            return n; 
        }
#line 90 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy9:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy9;
	case 'E':
	case 'e':	goto yy12;
	default:	goto yy11;
	}
yy11:
	o1 = yyt1;
	o2 = YYCURSOR;
#line 35 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            double ans = stod(s);
            Number n;
            n.set_val_d64(ans);
            return n; 
        }
#line 123 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy17;
	case '+':
	case '-':	goto yy20;
	default:	goto yy13;
	}
yy13:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy8;
	} else {
		goto yy11;
	}
yy14:
	++YYCURSOR;
	goto yy8;
yy15:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR;
#line 65 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            auto ans = stoull(s);
            Number n;
            n.set_val_u64(ans);
            return n; 
        }
#line 166 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy17;
	default:	goto yy19;
	}
yy19:
	o1 = yyt1;
	o2 = YYCURSOR;
#line 45 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            double ans = stod(s);
            Number n;
            n.set_val_d64(ans);
            return n; 
        }
#line 196 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy17;
	default:	goto yy13;
	}
}
#line 74 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"

}