/* Generated by re2c 1.1.1 on Sun Mar 10 14:48:58 2019 */
#line 1 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
#include <stdio.h>
#include <algorithm>
#include <cinttypes>

#include "lexers/lexers.h"
using namespace std;

Number lex_number(const char *YYCURSOR)
{
	vector<Token> ans;
	const char *YYMARKER, *o1, *o2;
    const char *start = YYCURSOR;

	const char *yyt1;
	
loop:
    
#line 21 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
		yyt1 = YYCURSOR;
		goto yy4;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = YYCURSOR;
		goto yy5;
	default:	goto yy2;
	}
yy2:
	++YYCURSOR;
yy3:
#line 31 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            Number n{};
            return n; 
        }
#line 50 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'B':
	case 'b':	goto yy6;
	case 'X':
	case 'x':	goto yy8;
	default:	goto yy3;
	}
yy5:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:	goto yy9;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy11;
	case '.':	goto yy13;
	case 'E':
	case 'e':	goto yy15;
	case 'S':
	case 's':	goto yy16;
	case 'U':
	case 'u':	goto yy17;
	default:	goto yy3;
	}
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':	goto yy18;
	default:	goto yy7;
	}
yy7:
	YYCURSOR = YYMARKER;
	goto yy3;
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy20;
	default:	goto yy7;
	}
yy9:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 96 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            // Todo: Make something smarter here
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());
            s.erase(std::remove(s.begin(), s.end(), 'S'), s.end());
            s.erase(std::remove(s.begin(), s.end(), 's'), s.end());

            auto ans = stoll(s);
            Number n;
            n.set_val_i64(ans);
            return n; 
        }
#line 139 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy9;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy11;
	case '.':	goto yy13;
	case 'E':
	case 'e':	goto yy15;
	case 'S':
	case 's':	goto yy16;
	case 'U':
	case 'u':	goto yy17;
	default:	goto yy7;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy22;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy13;
	case 'E':
	case 'e':	goto yy15;
	default:	goto yy7;
	}
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy7;
	case '+':
	case '-':	goto yy26;
	default:	goto yy25;
	}
yy16:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy9;
	goto yy7;
yy17:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy27;
	goto yy7;
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy29;
	case '\'':
	case '0':
	case '1':	goto yy18;
	case 'S':
	case 's':	goto yy31;
	case 'U':
	case 'u':	goto yy32;
	default:	goto yy7;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy33;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy20;
	case 'S':
	case 's':	goto yy35;
	case 'U':
	case 'u':	goto yy36;
	default:	goto yy7;
	}
yy22:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 76 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            double ans = stod(s);
            Number n;
            n.set_val_d64(ans);
            return n; 
        }
#line 259 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy24:
	yych = *++YYCURSOR;
yy25:
	switch (yych) {
	case 0x00:	goto yy37;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy24;
	default:	goto yy7;
	}
yy26:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy7;
	goto yy25;
yy27:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 109 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            auto ans = stoull(s);
            Number n;
            n.set_val_u64(ans);
            return n; 
        }
#line 296 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy29:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 36 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            uint64_t val = 0;
            uint64_t place = 0;
            for(int i = s.size() - 1; i >= 0; i--){
                if(s[i] == 'u' || s[i] == 'U')
                    continue;
                
                int place_value = s[i] == '1' ? 1 : 0;
                place_value = place_value << place++;
                val += place_value;
            }
            
            Number n;
            n.set_val_u64(val);
            return n; 
        }
#line 321 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy31:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy39;
	goto yy7;
yy32:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy29;
	goto yy7;
yy33:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 119 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            auto ans = stoull(s, 0, 16);
            Number n;
            n.set_val_u64(ans);
            return n; 
        }
#line 344 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy35:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy41;
	goto yy7;
yy36:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy33;
	goto yy7;
yy37:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 86 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            double ans = stod(s);
            Number n;
            n.set_val_d64(ans);
            return n; 
        }
#line 367 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy39:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 56 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            int64_t val = 0;
            int64_t place = 0;
            for(int i = s.size() - 1; i >= 0; i--){
                if(s[i] == 's' || s[i] == 'S')
                    continue;
                
                int place_value = s[i] == '1' ? 1 : 0;
                place_value = place_value << place++;
                val += place_value;
            }
            
            Number n;
            n.set_val_i64(val);
            return n; 
        }
#line 392 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
yy41:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 129 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            // Todo: Make something smarter here
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());
            s.erase(std::remove(s.begin(), s.end(), 'S'), s.end());
            s.erase(std::remove(s.begin(), s.end(), 's'), s.end());

            auto ans = stoull(s, 0, 16);
            Number n;
            n.set_val_i64(ans);
            return n; 
        }
#line 410 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.cc"
}
#line 141 "/cygdrive/C/repos/scalc/lexers/lexer_numlit.re"

}