/* Generated by re2c 1.0.1 on Sun Mar 24 22:19:22 2019 */
#line 1 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.re"
#include <stdio.h>
#include <algorithm>
#include <cinttypes>

#include "lexers/lexers.h"
using namespace std;

Number lex_number(const char *YYCURSOR)
{
	vector<Token> ans;
	const char *YYMARKER, *o1, *o2;
    const char *start = YYCURSOR;

	const char *yyt1;
	
loop:
    
#line 21 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.cc"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
		yyt1 = YYCURSOR;
		goto yy2;
	case '\'':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = YYCURSOR;
		goto yy6;
	case '.':
		yyt1 = YYCURSOR;
		goto yy7;
	case '0':
		yyt1 = YYCURSOR;
		goto yy8;
	case 'E':
	case 'e':
		yyt1 = YYCURSOR;
		goto yy9;
	case 'S':
	case 's':
		yyt1 = YYCURSOR;
		goto yy10;
	case 'U':
	case 'u':
		yyt1 = YYCURSOR;
		goto yy11;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 76 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            double ans = stod(s);
            Number n;
            n.set_val_d64(ans);
            return n; 
        }
#line 75 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.cc"
yy4:
	++YYCURSOR;
yy5:
#line 31 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.re"
	{ 
            Number n{};
            return n; 
        }
#line 84 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.cc"
yy6:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:	goto yy2;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy12;
	case '.':	goto yy15;
	case 'E':
	case 'e':	goto yy17;
	case 'S':
	case 's':	goto yy18;
	case 'U':
	case 'u':	goto yy19;
	default:	goto yy5;
	}
yy7:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:	goto yy2;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy15;
	case 'E':
	case 'e':	goto yy17;
	default:	goto yy5;
	}
yy8:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:	goto yy2;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy12;
	case '.':	goto yy15;
	case 'B':
	case 'b':	goto yy20;
	case 'E':
	case 'e':	goto yy17;
	case 'S':
	case 's':	goto yy18;
	case 'U':
	case 'u':	goto yy19;
	case 'X':
	case 'x':	goto yy21;
	default:	goto yy5;
	}
yy9:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy22;
	case '+':
	case '-':	goto yy24;
	default:	goto yy5;
	}
yy10:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy25;
	goto yy5;
yy11:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy27;
	goto yy5;
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy12;
	case '.':	goto yy15;
	case 'E':
	case 'e':	goto yy17;
	case 'S':
	case 's':	goto yy18;
	case 'U':
	case 'u':	goto yy19;
	default:	goto yy14;
	}
yy14:
	YYCURSOR = YYMARKER;
	goto yy5;
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy15;
	case 'E':
	case 'e':	goto yy17;
	default:	goto yy14;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy14;
	case '+':
	case '-':	goto yy24;
	default:	goto yy23;
	}
yy18:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy25;
	goto yy14;
yy19:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy27;
	goto yy14;
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':	goto yy29;
	default:	goto yy14;
	}
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy31;
	default:	goto yy14;
	}
yy22:
	yych = *++YYCURSOR;
yy23:
	switch (yych) {
	case 0x00:	goto yy33;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy22;
	default:	goto yy14;
	}
yy24:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy14;
	goto yy23;
yy25:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 96 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            // Todo: Make something smarter here
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());
            s.erase(std::remove(s.begin(), s.end(), 'S'), s.end());
            s.erase(std::remove(s.begin(), s.end(), 's'), s.end());

            auto ans = stoll(s);
            Number n;
            n.set_val_i64(ans);
            return n; 
        }
#line 318 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.cc"
yy27:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 109 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            auto ans = stoull(s);
            Number n;
            n.set_val_u64(ans);
            return n; 
        }
#line 333 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.cc"
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy35;
	case '\'':
	case '0':
	case '1':	goto yy29;
	case 'S':
	case 's':	goto yy37;
	case 'U':
	case 'u':	goto yy38;
	default:	goto yy14;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy39;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy31;
	case 'S':
	case 's':	goto yy41;
	case 'U':
	case 'u':	goto yy42;
	default:	goto yy14;
	}
yy33:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 86 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            double ans = stod(s);
            Number n;
            n.set_val_d64(ans);
            return n; 
        }
#line 394 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.cc"
yy35:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 36 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            uint64_t val = 0;
            uint64_t place = 0;
            for(int i = s.size() - 1; i >= 0; i--){
                if(s[i] == 'u' || s[i] == 'U')
                    continue;
                
                int place_value = s[i] == '1' ? 1 : 0;
                place_value = place_value << place++;
                val += place_value;
            }
            
            Number n;
            n.set_val_u64(val);
            return n; 
        }
#line 419 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.cc"
yy37:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy43;
	goto yy14;
yy38:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy35;
	goto yy14;
yy39:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 119 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            auto ans = stoull(s, 0, 16);
            Number n;
            n.set_val_u64(ans);
            return n; 
        }
#line 442 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.cc"
yy41:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy45;
	goto yy14;
yy42:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy39;
	goto yy14;
yy43:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 56 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());

            int64_t val = 0;
            int64_t place = 0;
            for(int i = s.size() - 1; i >= 0; i--){
                if(s[i] == 's' || s[i] == 'S')
                    continue;
                
                int place_value = s[i] == '1' ? 1 : 0;
                place_value = place_value << place++;
                val += place_value;
            }
            
            Number n;
            n.set_val_i64(val);
            return n; 
        }
#line 475 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.cc"
yy45:
	++YYCURSOR;
	o1 = yyt1;
	o2 = YYCURSOR - 1;
#line 129 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.re"
	{ 
            string s(o1, o2);
            // Todo: Make something smarter here
            s.erase(std::remove(s.begin(), s.end(), '\''), s.end());
            s.erase(std::remove(s.begin(), s.end(), 'S'), s.end());
            s.erase(std::remove(s.begin(), s.end(), 's'), s.end());

            auto ans = stoull(s, 0, 16);
            Number n;
            n.set_val_i64(ans);
            return n; 
        }
#line 493 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.cc"
}
#line 141 "/mnt/c/repos/scalc/build/../lexers/lexer_numlit.re"

}